### PR TITLE
More clear and readable README

### PR DESCRIPTION
**Pull request by MoOx**
Here are my 2 other cents ;)

### CODE REVIEW

**Comment by ai** [comment]
@MoOx BTW why we use blockquote for main project description? It is gray and hides most important text.

**Comment by MoOx** [comment]
A lot of project are doing that.
For me it's the only way to make a part of text in another color than the normal one. I don't think it hiding the text but make it more like a more visible quote. The only thing you should read. But that's only my point of view :) You should ask other about that.

**Comment by ai** [comment]
Yeap, I saw it very widly in npm community, but I think it is a bad practice like any other gray text.

**Comment by gazay** [comment]
Thank you @MoOx !

**Comment by gazay** [comment]
@ai as I see – most others postcss plugins have this kind of style for description. If we'll change it all – we'll change it here too. But I don't mind if it will be gray

**Pull request merged**
